modmap:
  - name: capslock as control and escape
    remap:
      CapsLock:
        held: Ctrl_L
        alone: Esc
        alone_timeout_millis: 200

  - name: swap shift_r with backspace
    remap:
      Shift_R: Backspace

  - name: block_doubleclick
    remap:
      BTN_LEFT:
        debounce:
          delay_ms: 800

keymap:
  - name: swap asciitilde with grave
    device:
    remap:
      Shift-grave: grave
      grave: Shift-grave

  - name: henkan mode to right
    remap:
      Henkan: Right

  - name: control-h as backspace
    remap:
      Ctrl_L-h: Backspace
