[colors]
draw_bold_text_with_bright_colors = true

[colors.cursor]
cursor = '#FFA500' # This sets the color of the cursor itself
text = '#FFA500' # This sets the color of the text *underneath* the cursor

[[colors.indexed_colors]]
color = "0xff966c"
index = 16

[[colors.indexed_colors]]
color = "0xc53b53"
index = 17

[colors.bright]
black = "0x444a73"
blue = "0x82aaff"
cyan = "0x86e1fc"
green = "0xc3e88d"
magenta = "0xc099ff"
red = "0xff757f"
white = "0xc8d3f5"
yellow = "0xffc777"

[colors.normal]
black = "0x1b1d2b"
blue = "0x82aaff"
cyan = "0x86e1fc"
green = "0xc3e88d"
magenta = "0xc099ff"
red = "0xff757f"
white = "0x828bb8"
yellow = "0xffc777"

[colors.primary]
background = "0x222436"
foreground = "0xc8d3f5"

[font]
size = 10

[font.normal]
family = "caskaydiacove nerd font"
style = "bold"

[font.italic]
family = "caskaydiacove nerd font"
style = "bold italic"

[font.bold]
family = "caskaydiacove nerd font"
style = "bold"

[font.offset]
x = 0
y = 1

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "X"
mods = "Control"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Space"
mods = "Control"

[[keyboard.bindings]]
action = "toggleViMode"
key = "J"
mods = "Control"

[[keyboard.bindings]]
key = "Minus"
mods = "Control"
action = "None"

[[keyboard.bindings]]
key = "Equals"
mods = "Control"
action = "None"

[window]
dynamic_padding = false

[window.padding]
x = 14
y = 7

# [cursor]
# style = { shape = "Beam", blinking = "Never" }
# thickness = 0.1
